apiVersion: apps/v1
kind: Deployment

metadata:
  name: machine-learning-api-deployment
  labels:
    app: machine-learning-api

spec:
  replicas: 2  # Adjust replicas as needed
  selector:
    matchLabels:
      app: machine-learning-api
  template:
    metadata:
      labels:
        app: machine-learning-api
    spec:
      containers:
        - name: machine-learning-api
          image: talisma/prod.machine-learning.stack
          ports:
            - containerPort: 5000
            - containerPort: 5555
          env:
            - name: IMAGEZMQ_SERVER
              value: "0.0.0.0:5555"  # Replace 'your-pc-ip' with actual IP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
