apiVersion: v1
kind: Service

metadata:
  name: machine-learning-api-service
  labels:
    app: machine-learning-api

spec:
  selector:
    app: machine-learning-api
  type: ClusterIP
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    protocol: TCP
  - name: imagezmq
    port: 5555
    targetPort: 5555
    protocol: TCP
